### ISSUE TITLE
Question: argument declaration

### ISSUE THREAD

**Issue by nastia-shaternik** [properati/quickblox-rb#4]
Hey ya,

could you please explain the meaning of such argument declaration for the method?

```ruby
def get_user(id:)
# ...
end

```

Thanx in advance for your answer.

**Comment by nastia-shaternik** [comment]
really, I've googled bad :)

https://robots.thoughtbot.com/ruby-2-keyword-arguments

sorry for disturbing.

**Comment by tonchis** [comment]
Hah! exactly. I was about to write that :)

It's not a problem, don't worry.
